name: Deploy to Live Channel

on:
  push:
    branches:
      - main
    # Optionally configure to run only for specific files. For example:
    # paths:
    # - "website/**"

jobs:
  deploy_live_website:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: ./site-new/joysteem
    steps:
      - uses: actions/checkout@v3
      # Add any build steps here. For example:
      - run: cp -a ./nopub_pagesrc/mainsite/build/. ./
      - run: cp -a ./nopub_pagesrc/quiz/build/. ./quiz
      - run: cp -a ./nopub_pagesrc/halflifemenu/build/. ./srcmenu
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_JOYSTEEM }}"
          projectId: joysteem
          channelId: live